name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: testing
      run: make tests
    - name: build_cli
      run: make nav_cli
    - name: style/static check
      run: make check
